### ISSUE TITLE
Set up CI to publish

### ISSUE THREAD

**Issue by rossiam** [SmartThingsCommunity/generator-smartthings#11]
The [Node SDK](https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/blob/master/.circleci/config.yml) can be used as an example.

**Comment by erodewald** [comment]
I had trouble getting the `nyc_output` json to upload to codecov, and I found a different way to do it by adding the `codecov` package to `devDependencies`. Take a look at the changes I made in the dynamodb lib: [dynamodb-context-store-nodejs/tree/master/.circleci/config.yml][1]

[1]: https://github.com/SmartThingsCommunity/dynamodb-context-store-nodejs/commit/a084914cd68b2f1964164093c2ffc9b202ece6ef#diff-1d37e48f9ceff6d8030570cd36286a61
